version: "3"

services:
  redis:
    container_name: redis-server
    image: redis:7.0.5
    restart: always
    ports:
      - "6379:6379"
    command: redis-server /usr/local/conf/redis.conf
    volumes:
      - ./conf/redis.conf:/usr/local/conf/redis.conf
